/**
 * Phase 17.0 comparison prototype — the 8 hand-authored fixtures
 * required by the comparison_prototype.fixtures list. NOT used by
 * production code, NOT generated by the real map generator (no RNG
 * consumed) — every grid here is a literal, hand-written string array.
 * See grid.ts's header comment.
 */
import { Grid, Point, Room, parseGrid } from './grid';

export interface Fixture {
  id: string;
  grid: Grid;
  origin: Point;
  room?: Room;
  notes: string;
}

export const straightCorridor: Fixture = {
  id: 'straight_corridor',
  grid: parseGrid(['###########', '#.........#', '###########']),
  origin: { x: 5, y: 1 },
  notes: 'A single straight 1-wide corridor: verifies visibility radius and that the corridor walls (not floor beyond the ends) bound it.',
};

export const lCorner: Fixture = {
  id: 'l_corner',
  grid: parseGrid(['#########', '#.......#', '#.#######', '#.#######', '#.#######', '#########']),
  origin: { x: 1, y: 3 },
  notes: 'An L-shaped corridor: verifies whether visibility leaks around the corner into the perpendicular leg farther than the corner tile itself, and diagonal peeking at the bend.',
};

export const doorwayFromRoom: Fixture = {
  id: 'doorway_from_room',
  grid: parseGrid([
    '###########',
    '#.........#',
    '#.........#',
    '#.........#',
    '#####.#####',
    '######.####',
    '######.####',
  ]),
  room: { x: 1, y: 1, width: 9, height: 3 },
  origin: { x: 5, y: 2 },
  notes: 'Standing inside a room with a single south doorway: verifies the whole room is visible and exactly the corridor\'s first tile below the doorway is visible, nothing past it.',
};

export const doorwayFromCorridor: Fixture = {
  id: 'doorway_from_corridor',
  grid: parseGrid([
    '###########',
    '#.........#',
    '#.........#',
    '#.........#',
    '#####.#####',
    '######.####',
    '######.####',
  ]),
  room: { x: 1, y: 1, width: 9, height: 3 },
  origin: { x: 6, y: 6 },
  notes: 'Standing in the corridor approaching the same doorway from outside: verifies when/whether the room\'s full-visibility rule should start (only once inside the rectangle, per this repo\'s existing roomIndexContaining-based rule) versus a radius-based partial view from the corridor.',
};

export const multipleExitsRoom: Fixture = {
  id: 'multiple_exits_room',
  grid: parseGrid([
    '#####.#####',
    '#.........#',
    '#.........#',
    '#.........#',
    '..........#',
    '#.........#',
    '#.........#',
    '#.........#',
    '#####.#####',
  ]),
  room: { x: 1, y: 1, width: 9, height: 7 },
  origin: { x: 5, y: 4 },
  notes: 'A room with 3 real doorways (N, S, W): verifies every genuine doorway is found and that the entrance-detection scan (one ring outside the rectangle) does not miss any of several simultaneous exits.',
};

export const diagonalDoubleWall: Fixture = {
  id: 'diagonal_double_wall',
  grid: parseGrid(['#####', '#.#.#', '##.##', '#.#.#', '#####']),
  origin: { x: 1, y: 1 },
  notes: 'A floor tile (2,2) reachable from the origin only by cutting diagonally between two wall corners ((2,1) and (1,2), both walls): verifies the candidate does not reveal through that diagonal gap, matching this repo\'s existing no-corner-cutting movement rule.',
};

export const mapEdge: Fixture = {
  id: 'map_edge',
  grid: parseGrid(['####', '#..#', '#..#', '####']),
  origin: { x: 1, y: 1 }, // one tile from two map edges at once
  notes: 'Origin near a map corner: verifies no out-of-bounds coordinates are ever produced and behavior stays stable at the edge/corner.',
};

export const darkRoom: Fixture = {
  id: 'dark_room',
  grid: parseGrid([
    '#############',
    '#...........#',
    '#...........#',
    '#...........#',
    '#...........#',
    '#...........#',
    '#############',
  ]),
  room: { x: 1, y: 1, width: 11, height: 5 },
  origin: { x: 3, y: 3 },
  notes: 'A large room, used to compare the dark-area override (small fixed radius, e.g. 2 or 3) against the normal whole-room-visible rule the same room would otherwise get.',
};

export const ALL_FIXTURES: Fixture[] = [
  straightCorridor,
  lCorner,
  doorwayFromRoom,
  doorwayFromCorridor,
  multipleExitsRoom,
  diagonalDoubleWall,
  mapEdge,
  darkRoom,
];
